In [175]:
import pandas as pd
import numpy as np

In [176]:
tweets_df = pd.read_csv("Tweets11122022.csv")
tweets_df = tweets_df.drop(3892).reset_index()
tweets_df.head()

,index,Unnamed: 0,Name,Twitter Handle,Time,Content,Retweeting,Hashtags,Mentions,Annotations,URLs,Context Annotations
0,0,0,Alma Adams,RepAdams,2022-11-10 17:37:18+00:00,RT @HBCUCaucus: The HBCU Caucus Partnership Ch...,HBCUCaucus,[],['HBCUCaucus'],['Other:HBCU Caucus Partnership Challenge'],[],"['Person,Alma Adams,US Representative Alma Ada..."
1,1,1,Alma Adams,RepAdams,2022-11-10 17:36:46+00:00,The @HBCUCaucus Partnership Challenge is an ef...,$,['HBCUs'],"['HBCUCaucus', 'abbvie', 'Amgen', 'ProtectiveL...",['Other:HBCUs'],['https://adams.house.gov/media-center/press-r...,"['Person,Alma Adams,US Representative Alma Ada..."
2,2,2,Alma Adams,RepAdams,2022-11-10 16:12:04+00:00,"This week, as our country observes #VeteransDa...",$,['VeteransDay'],[],"['Person:Pamela Helms', 'Organization:US Army'...",['https://twitter.com/RepAdams/status/15907390...,"['Person,Alma Adams,US Representative Alma Ada..."
3,3,3,Alma Adams,RepAdams,2022-11-10 14:52:18+00:00,Today is the 247th birthday of the @USMC. To t...,$,[],['USMC'],['Place:United States'],['https://twitter.com/RepAdams/status/15907190...,"['Person,Alma Adams,US Representative Alma Ada..."
4,4,4,Alma Adams,RepAdams,2022-11-08 22:15:14+00:00,If you’re in line to vote by 7:30 PM in North ...,$,[],[],['Place:North Carolina'],[],"['Person,Alma Adams,US Representative Alma Ada..."

In [177]:
#First I want to create a dataset of nodes for the tweets
tweet_nodes = pd.DataFrame({"id:ID(Tweet)" : np.array(tweets_df.index), "Content" : np.array(tweets_df.Content), "Time" : np.array(tweets_df.Time), ":LABEL" : np.repeat("Tweet", len(tweets_df.index))})
tweet_nodes.to_csv("nodes/tweets.csv", index = False)

In [178]:
tweet_nodes

,id:ID(Tweet),Content,Time,:LABEL
0,0,RT @HBCUCaucus: The HBCU Caucus Partnership Ch...,2022-11-10 17:37:18+00:00,Tweet
1,1,The @HBCUCaucus Partnership Challenge is an ef...,2022-11-10 17:36:46+00:00,Tweet
2,2,"This week, as our country observes #VeteransDa...",2022-11-10 16:12:04+00:00,Tweet
3,3,Today is the 247th birthday of the @USMC. To t...,2022-11-10 14:52:18+00:00,Tweet
4,4,If you’re in line to vote by 7:30 PM in North ...,2022-11-08 22:15:14+00:00,Tweet
5,5,"You have 2 1/2 hours left to vote, North Carol...",2022-11-08 21:54:17+00:00,Tweet
6,6,Have you voted yet?,2022-11-08 19:36:12+00:00,Tweet
7,7,"Charlotte, please go vote today! \n\nYou can c...",2022-11-08 16:37:36+00:00,Tweet
8,8,Are you a first time voter this #Election2022?...,2022-11-08 16:33:58+00:00,Tweet
9,9,RT @RepNikema: It’s #Election2022 &amp; every ...,2022-11-08 14:25:21+00:00,Tweet
10,10,RT @CATSRideTransit: FREE FARE ON ELECTION DAY...,2022-11-08 05:00:48+00:00,Tweet
11,11,You have the power to shape your future and ma...,2022-11-07 19:04:52+00:00,Tweet
12,12,RT @SMHSSabres: Vote!!! https://t.co/mZlCqmRhnX,2022-11-07 16:10:24+00:00,Tweet
13,13,Happy Veterans Day to all who have served and ...,2022-11-11 20:40:58+00:00,Tweet
14,14,Join me in wishing a Happy Birthday to the Mar...,2022-11-10 16:29:11+00:00,Tweet
15,15,I'm very sorry to hear this news. Jeff's musi...,2022-11-08 21:41:57+00:00,Tweet
16,16,Americans benefit from common-sense conservati...,2022-11-07 19:59:27+00:00,Tweet
17,17,"On #VeteransDay, we recommit ourselves to hono...",2022-11-11 16:48:45+00:00,Tweet
18,18,Happy #VeteransDay to all the outstanding men ...,2022-11-11 17:01:12+00:00,Tweet
19,19,Great to see such a major investment in the 12...,2022-11-07 23:42:25+00:00,Tweet
20,20,"Happy birthday to my wonderful husband, Rick. ...",2022-11-07 21:30:16+00:00,Tweet
21,21,Had a great time tailgating and attending the ...,2022-11-06 18:57:12+00:00,Tweet
22,22,"As a father, I know how critical those first m...",2022-11-12 20:00:01+00:00,Tweet
23,23,"Folks, open enrollment at https://t.co/77sYvUa...",2022-11-12 17:00:01+00:00,Tweet
24,24,Capturing the memories and sharing the stories...,2022-11-11 17:00:01+00:00,Tweet
25,25,It is my greatest honor to serve our veterans ...,2022-11-11 15:00:02+00:00,Tweet
26,26,Interested in learning about working in Congre...,2022-11-11 00:00:00+00:00,Tweet
27,27,I voted for the Inflation Reduction Act to hel...,2022-11-10 21:12:14+00:00,Tweet
28,28,"Today, we celebrate 247 years of the @USMC. To...",2022-11-10 16:10:58+00:00,Tweet
29,29,Thank you to all the poll workers and official...,2022-11-09 20:34:26+00:00,Tweet
...,...,...,...,...
6004,6004,West Virginians continue to raise concerns abo...,2022-11-07 13:10:41+00:00,Tweet
6005,6005,Interest rates continue to climb because of ou...,2022-11-06 15:50:57+00:00,Tweet
6006,6006,"Current policies, including the so-called Infl...",2022-11-05 23:14:51+00:00,Tweet
6007,6007,I disagree with President Biden’s statement re...,2022-11-05 23:06:02+00:00,Tweet
6008,6008,I'm proud to assist Veterans like Mr. Kirkham ...,2022-11-11 16:46:00+00:00,Tweet
6009,6009,"Happy #VeteransDay! Today and every day, pleas...",2022-11-11 12:30:00+00:00,Tweet
6010,6010,Join me in praying for safety of the firefight...,2022-11-10 19:33:55+00:00,Tweet
6011,6011,I greatly appreciate Kroger CEO Rodney McMulle...,2022-11-10 16:31:27+00:00,Tweet
6012,6012,When I heard last week that the Gassaway Kroge...,2022-11-10 16:31:27+00:00,Tweet
6013,6013,"Happy 247th Birthday to the @USMarineCorps, an...",2022-11-10 15:03:47+00:00,Tweet
6014,6014,Happy #ElectionDay! The polls are open across ...,2022-11-08 11:30:00+00:00,Tweet
6015,6015,"It was great to be back home in Farmington, WV...",2022-11-07 15:26:04+00:00,Tweet
6016,6016,No West Virginian should have to choose betwee...,2022-11-06 21:03:00+00:00,Tweet
6017,6017,Election Day is just two days away! Make a pla...,2022-11-06 13:58:00+00:00,Tweet
6018,6018,Students at Casper’s CY Middle School and Dean...,2022-11-11 23:24:44+00:00,Tweet
6019,6019,U.S. Marine Leo Sanchez was a lifelong veteran...,2022-11-11 22:24:17+00:00,Tweet
6020,6020,No one kicks off #VeteransDay quite like Dougl...,2022-11-11 21:14:48+00:00,Tweet
6021,6021,"Today and every day, we honor our veterans who...",2022-11-11 15:12:31+00:00,Tweet
6022,6022,The Kiwanis Club of Casper is no stranger to g...,2022-11-10 20:56:52+00:00,Tweet
6023,6023,Everyday life is too expensive in Wyoming and ...,2022-11-10 13:55:15+00:00,Tweet
6024,6024,Congrats to Harriet Hageman on her decisive vi...,2022-11-09 04:15:19+00:00,Tweet
6025,6025,Wyoming is the coal capital of the United Stat...,2022-11-07 22:08:01+00:00,Tweet
6026,6026,The Cowboys Against Cancer 26th Annual Benefit...,2022-11-06 02:03:08+00:00,Tweet
6027,6027,People in Wyoming place a high value of trust ...,2022-11-11 22:12:34+00:00,Tweet
6028,6028,It's clearer now than ever before that we need...,2022-11-11 21:29:38+00:00,Tweet
6029,6029,"Today, we honor those who have sacrificed so m...",2022-11-11 16:02:16+00:00,Tweet
6030,6030,The EPA denying small refineries an exemption ...,2022-11-10 16:29:13+00:00,Tweet
6031,6031,It’s time for Congress to cut government spend...,2022-11-09 23:39:33+00:00,Tweet
6032,6032,RT @SenJohnBarrasso: Congrats to Harriet Hagem...,2022-11-09 04:24:52+00:00,Tweet
6033,6033,I have many questions regarding Binance acquir...,2022-11-08 22:33:59+00:00,Tweet

In [179]:
#Now I want to create relationships between each tweet and the tweeter
tweet_id = np.array(tweets_df.index)
tweeter = np.array(tweets_df.Name)

tweet_relationships = pd.DataFrame({":START_ID(Congresspeople-ID)" : tweeter, ":END_ID(Tweet)" : tweet_id, ":TYPE" : np.repeat("tweeted", len(tweet_id))})
tweet_relationships.to_csv("relationships/congressperson_to_tweet.csv", index = False)
tweet_relationships.head()

  :START_ID(Congresspeople-ID)  :END_ID(Tweet)    :TYPE
0                   Alma Adams               0  tweeted
1                   Alma Adams               1  tweeted
2                   Alma Adams               2  tweeted
3                   Alma Adams               3  tweeted
4                   Alma Adams               4  tweeted

In [195]:
#Now I'm going to create edges from each tweet to its hashtags
hashtags = []
origin_tweet = []
for i in range(len(tweets_df.index)):
    hashtag = "".join(str(tweets_df['Hashtags'][i])[1:-1].split("'")).split(", ")
    for h in hashtag:
        if h != '':
            hashtags.append(h)
            origin_tweet.append(i)
            
hashtags_relationships = pd.DataFrame({":START_ID(Tweet)" : origin_tweet, ":END_ID(Hashtag)" : hashtags, ":TYPE" : np.repeat("has hashtag", len(hashtags))})
hashtag_df = pd.DataFrame({"hashtag:ID(Hashtag)" : np.unique(hashtags), ":LABEL" : np.repeat("Hashtag", len(np.unique(hashtags)))})
hashtags_relationships.to_csv("relationships/hashtag_relationships.csv", index = False)
hashtag_df.to_csv("nodes/hashtags.csv", index = False)
hashtags_relationships.head()

   :START_ID(Tweet) :END_ID(Hashtag)        :TYPE
0                 1            HBCUs  has hashtag
1                 2      VeteransDay  has hashtag
2                 8     Election2022  has hashtag
3                 9     Election2022  has hashtag
4                17      VeteransDay  has hashtag

In [191]:
#Now I'm going to extract the annotations
annotations = []
annotation_type = []
annotation_target = []
origin_tweet = []
for i in range(len(tweets_df.index)):
    annotation = "".join(str(tweets_df['Annotations'][i])[1:-1].split("'")).split(", ")
    for a in annotation:
        if a != '':
            try:
                annotations.append(a)
                annotation_type.append(a.split(":")[0].replace('"', ""))
                annotation_target.append(a.split(":")[1].replace('"', ""))
                origin_tweet.append(i)
            except Exception as e:
                print(e, a, i)

annotations = np.array(annotations)
annotation_type = np.array(annotation_type)
annotation_target = np.array(annotation_target)
origin_tweet = np.array(origin_tweet)

annotation_types = np.unique(annotation_type)

for at in annotation_types:
    targets_filtered = np.array(np.unique(annotation_target[annotation_type == at]))
    targets_df = pd.DataFrame({"name:ID(" + at + ")" : targets_filtered, ":LABEL" : np.repeat(at, len(targets_filtered))})
    targets_df.to_csv("nodes/" + at.lower() + ".csv", index = False)
                      
    targets_start = origin_tweet[annotation_type == at]
    targets_end = annotation_target[annotation_type == at]
    relationships_filtered = pd.DataFrame({":START_ID(Tweet)" : targets_start, ":END_ID(" + at + ")" : targets_end, ":TYPE" : np.repeat("references", len(targets_start))})
    relationships_filtered.to_csv("relationships/" + at.lower() + "_relationships.csv", index = False)

In [196]:
origin_tweet = []
types = []
targets = []
specifications = []
for i in range(len(tweets_df.index)):
    cannotation = tweets_df['Context Annotations'][i][1:-1].split("',")
    for ca in cannotation:
        if ca[:1] == "'" or ca[:1] == '"':
            ca = ca[1:]
        elif ca[:2] == " '" or ca[:2] == ' "':
            ca = ca[2:]
        if ca[:1] == '"':
            ca = ca[1:]
            
        if ca[-1:] == '"' or ca[-1:] == "'":
            ca = ca[:-1]
        ca = ca.split(",")
        if len(ca) < 2:
            print(ca, end = "\r")
        else:
            origin_tweet.append(i)
            types.append(ca[0])
            targets.append(ca[1])
            if len(ca) > 2:
                specifications.append(",".join(ca[2:]))
            else:
                specifications.append('')
                
origin_tweet = np.array(origin_tweet)
types = np.array(types)
targets = np.array(targets)
specifications = np.array(specifications)

unique_types = np.unique(types)
for ut in unique_types:
    idx = np.where(types == ut)
    
    targets_filtered = targets[idx]
    origins_filtered = origin_tweet[idx]
    specifications_filtered = specifications[idx]
    
    targets_df = pd.DataFrame({"name:ID(" + ut + "-ca)" : np.unique(targets_filtered), ":LABEL" : np.repeat(ut, len(np.unique(targets_filtered)))})
    relationships_filtered = pd.DataFrame({":START_ID(Tweet)" : origins_filtered, ":END_ID(" + ut + "-ca)" : targets_filtered, ":TYPE" : np.repeat("references", len(targets_filtered)), "Specification" : specifications_filtered})
    
    targets_df.to_csv("nodes/" + ut.lower() + "_ca.csv", index = False)
    relationships_filtered.to_csv("relationships/" + ut.lower() + "relationships_ca.csv", index = False)

In [186]:
np.unique(types)

array(['Actor', 'American Football Game', 'Athlete', 'Award Show',
       'Baseball Game', 'Basketball Game', 'Brand', 'Brand Vertical',
       'Business Taxonomy', 'Cities', 'Coach', 'Colleges & Universities',
       'Digital Assets & Crypto', 'Digital Creator', 'Emergency Events',
       'Entertainment Personality', 'Entities [Entity Service]',
       'Events [Entity Service]', 'Exercise & fitness', 'Fields of study',
       'Food', 'Global TV Show', 'Holiday', 'Interests and Hobbies',
       'Interests and Hobbies Category', 'Interests and Hobbies Vertical',
       'Journalist', 'Local News', 'Movie', 'Movie Genre',
       'Multimedia Franchise', 'Music Album', 'Music Genre', 'Musician',
       'NFL Football Game', 'News Vertical', 'Ongoing News Story',
       'Person', 'Place', 'Podcast', 'Political Body', 'Political Race',
       'Politician', 'Product', 'Product Taxonomy', 'Reoccurring Trends',
       'Soccer Match', 'Sport', 'Sports Event', 'Sports League',
       'Sports Personality', 'Sports Team', 'States', 'TV Shows',
       'Technology', 'Travel', 'Unified Twitter Taxonomy',
       'Video Game Publisher', 'Weather'], dtype='<U30')

In [141]:
idx = 5939
tweets_df['Name'][idx], tweets_df['Content'][idx]

('PatrickJ. Leahy',
 'In June, the State Dept rightly called on the Cambodian Gov’t to release “all those unjustly detained, including Theary Seng,” an American citizen human rights activist. Pres Biden should seek her release when he travels to Phenom Penh later this month.')